export const de = {
  search: "Knoten suchen…",
  focus: "Fokusknoten",
  all: "Gesamter Graph",
  local: "Nachbarschaft",
  depth: "Tiefe",
  groups: "Entitätsgruppen",
  labels: "Alle Namen",
  zoomIn: "Vergrößern",
  zoomOut: "Verkleinern",
  reset: "Ansicht zurücksetzen",
  instructions:
    "Ziehen zum Verschieben · Scrollen zum Zoomen · Knoten verschieben. Tastatur: Pfeiltasten, + / − zum Zoomen, 0 zum Zurücksetzen.",
  inspector: "Knoteninspektor",
  choose: "Knoten zum Erkunden auswählen",
  connections: "Verbindungen",
  nodes: "Knoten",
  edges: "Beziehungen",
  empty: "Keine Knoten entsprechen diesen Filtern.",
  list: "Tastaturnavigation · alle Knoten",
  fit: "Graph einpassen",
  spread: "Abstand",
  overview: "Interaktiver Beziehungsgraph",
  relationship: "Beziehung",
  graphIntro:
    "Verbindungen zwischen Kunden, Portfolios und Anlageklassen erkunden. Jede Kante stammt aus dem geladenen Portfolio-Snapshot.",
  ontologyIntro:
    "Das verbundene Datenmodell. Eine Entität auswählen, um ihre Verknüpfungen und die Regeln zur konsistenten Auslegung der Portfoliodaten zu prüfen.",
  sourceId: "Quellentität",
  count: "Verknüpfte Datensätze",
  entity: "Entität",
  ontology: "Datenmodell",
  entities: {
    Clients: "Kunden",
    Portfolios: "Portfolios",
    SecurityPositions: "Positionen",
    Securities: "Wertpapiere",
    StrategicAssetAllocations: "Zielallokationen",
    SuitabilityViolations: "Gemeldete Befunde",
    SuitabilityRules: "Eignungsregeln",
    RiskProfiles: "Risikoprofile",
    FundUnbundlingMappings: "Fondsaufschlüsselung",
    Transactions: "Transaktionen",
    Proposals: "Vorschläge",
  },
  relations: {
    ownership: "besitzt",
    security: "identifiziert",
    allocation: "hat Ziel",
    suitability: "verweist auf",
    risk: "hat Profil",
    lookthrough: "schlüsselt auf",
    proposal: "gehört zum Entwurf",
  },
};
