export const en = {
  search: "Find a node…",
  focus: "Focus node",
  all: "Whole graph",
  local: "Neighborhood",
  depth: "Depth",
  groups: "Entity groups",
  labels: "All labels",
  zoomIn: "Zoom in",
  zoomOut: "Zoom out",
  reset: "Reset view",
  instructions:
    "Drag to pan · scroll to zoom · drag a node to rearrange. Keyboard: arrows to pan, + / − to zoom, 0 to reset.",
  inspector: "Node inspector",
  choose: "Select a node to explore",
  connections: "connections",
  nodes: "nodes",
  edges: "relationships",
  empty: "No nodes match these filters.",
  list: "Keyboard navigation · browse all nodes",
  fit: "Fit graph",
  spread: "Spacing",
  overview: "Interactive relationship graph",
  relationship: "Relationship",
  graphIntro:
    "Explore the connections between clients, portfolios and asset classes. Every edge comes from the loaded portfolio snapshot.",
  ontologyIntro:
    "The data model, connected. Select an entity to inspect its joins and the interpretation rules that keep portfolio evidence consistent.",
  sourceId: "Source entity",
  count: "Linked records",
  entity: "Entity",
  ontology: "Data model",
  entities: {
    Clients: "Clients",
    Portfolios: "Portfolios",
    SecurityPositions: "Positions",
    Securities: "Securities",
    StrategicAssetAllocations: "Target allocations",
    SuitabilityViolations: "Reported findings",
    SuitabilityRules: "Suitability rules",
    RiskProfiles: "Risk profiles",
    FundUnbundlingMappings: "Fund look-through",
    Transactions: "Transactions",
    Proposals: "Proposals",
  },
  relations: {
    ownership: "owns",
    security: "identifies",
    allocation: "targets",
    suitability: "references",
    risk: "has profile",
    lookthrough: "looks through",
    proposal: "belongs to draft",
  },
};
