export const es = {
  search: "Buscar un nodo…",
  focus: "Nodo seleccionado",
  all: "Grafo completo",
  local: "Vecindario",
  depth: "Profundidad",
  groups: "Grupos de entidades",
  labels: "Etiquetas",
  zoomIn: "Acercar",
  zoomOut: "Alejar",
  reset: "Restablecer vista",
  instructions:
    "Arrastra para desplazar · rueda para ampliar · arrastra un nodo para moverlo. Teclado: flechas, + / − para ampliar, 0 para restablecer.",
  inspector: "Inspector de nodos",
  choose: "Selecciona un nodo para explorar",
  connections: "conexiones",
  nodes: "nodos",
  edges: "relaciones",
  empty: "Ningún nodo coincide con los filtros.",
  list: "Navegación con teclado · todos los nodos",
  fit: "Ajustar grafo",
  spread: "Separación",
  overview: "Grafo interactivo de relaciones",
  relationship: "Relación",
  graphIntro:
    "Explora las conexiones entre clientes, carteras y clases de activos. Cada enlace procede de la instantánea de carteras cargada.",
  ontologyIntro:
    "El modelo de datos, conectado. Selecciona una entidad para inspeccionar sus uniones y las reglas que mantienen la coherencia de la evidencia.",
  sourceId: "Entidad de origen",
  count: "Registros vinculados",
  entity: "Entidad",
  ontology: "Modelo de datos",
  entities: {
    Clients: "Clientes",
    Portfolios: "Carteras",
    SecurityPositions: "Posiciones",
    Securities: "Valores",
    StrategicAssetAllocations: "Asignaciones objetivo",
    SuitabilityViolations: "Hallazgos notificados",
    SuitabilityRules: "Reglas de idoneidad",
    RiskProfiles: "Perfiles de riesgo",
    FundUnbundlingMappings: "Desglose de fondos",
    Transactions: "Transacciones",
    Proposals: "Propuestas",
  },
  relations: {
    ownership: "posee",
    security: "identifica",
    allocation: "tiene objetivo",
    suitability: "referencia",
    risk: "tiene perfil",
    lookthrough: "desglosa",
    proposal: "pertenece al borrador",
  },
};
