export const fr = {
  search: "Rechercher un nœud…",
  focus: "Nœud sélectionné",
  all: "Graphe complet",
  local: "Voisinage",
  depth: "Profondeur",
  groups: "Groupes d’entités",
  labels: "Étiquettes",
  zoomIn: "Agrandir",
  zoomOut: "Réduire",
  reset: "Réinitialiser la vue",
  instructions:
    "Glisser pour déplacer · défiler pour zoomer · glisser un nœud pour le déplacer. Clavier : flèches, + / − pour zoomer, 0 pour réinitialiser.",
  inspector: "Inspecteur de nœuds",
  choose: "Sélectionnez un nœud à explorer",
  connections: "connexions",
  nodes: "nœuds",
  edges: "relations",
  empty: "Aucun nœud ne correspond aux filtres.",
  list: "Navigation au clavier · tous les nœuds",
  fit: "Ajuster le graphe",
  spread: "Espacement",
  overview: "Graphe interactif des relations",
  relationship: "Relation",
  graphIntro:
    "Explorez les connexions entre clients, portefeuilles et classes d’actifs. Chaque lien provient de l’instantané chargé des portefeuilles.",
  ontologyIntro:
    "Le modèle de données, relié. Sélectionnez une entité pour examiner ses jointures et les règles d’interprétation qui préservent la cohérence des preuves.",
  sourceId: "Entité source",
  count: "Enregistrements liés",
  entity: "Entité",
  ontology: "Modèle de données",
  entities: {
    Clients: "Clients",
    Portfolios: "Portefeuilles",
    SecurityPositions: "Positions",
    Securities: "Titres",
    StrategicAssetAllocations: "Allocations cibles",
    SuitabilityViolations: "Constats signalés",
    SuitabilityRules: "Règles d’adéquation",
    RiskProfiles: "Profils de risque",
    FundUnbundlingMappings: "Transparence des fonds",
    Transactions: "Transactions",
    Proposals: "Propositions",
  },
  relations: {
    ownership: "possède",
    security: "identifie",
    allocation: "cible",
    suitability: "référence",
    risk: "a pour profil",
    lookthrough: "décompose",
    proposal: "appartient au brouillon",
  },
};
