import type { AdminMessages } from "./messages";
export const de: AdminMessages = {
  adminView: "Administrationsansicht",
  adminHint: "Gemeinsame Demodaten und Laufzeit schreibgeschützt prüfen",
  advisorView: "Berateransicht",
  title: "Daten und Laufzeit",
  subtitle: "Die Belege hinter jedem Gespräch prüfen.",
  readonly: "Gemeinsame Demo · nur Lesen",
  disclosure:
    "Diese Ansicht nutzt Ihre bestehende Demositzung. Sie erteilt keine Administratorrechte und erlaubt keine Datenänderungen.",
  overview: "Übersicht",
  datasets: "Datensätze",
  structure: "Datenstruktur",
  "knowledge-graph": "Wissensgraph",
  ontology: "Ontologie",
  agents: "Agenten",
  skills: "Fähigkeiten",
  runtime: "Laufzeit",
  refresh: "Aktualisieren",
  refreshHint: "Datenanzahlen und aktuelle Laufzeitverfügbarkeit neu laden",
  checked: "Geprüft",
  sourceSnapshot: "Quellenstand",
  loadedData: "Geladene Daten",
  clients: "Kunden",
  portfolios: "Portfolios",
  holdings: "Positionen",
  violations: "Gemeldete Feststellungen",
  sourceCollections: "Quellensammlungen",
  documentTopics: "Wissensthemen",
  valuation: "Zeitraum der Risikoberechnung",
  dataWarning:
    "Quelldaten können zeitlich verschoben sein. Preis- und Risikoberechnungsdaten behalten ihre ursprüngliche Bedeutung.",
  missingYtd: "Portfolios ohne gelieferte Jahresperformance",
  missingHint:
    "Fehlende Performance ist nicht verfügbar und niemals null Prozent. Historische NAV-Veränderungen sind keine verifizierten Anlagerenditen.",
  sourceHint:
    "Diese Anzahlen und Felddefinitionen wurden aus den gelieferten JSON-Dateien erzeugt. Sie sind Metadaten und keine Live-Verbindung zum Quellsystem.",
  generated: "Katalog erstellt",
  records: "Datensätze",
  fields: "Felder",
  source: "Quelle",
  locator: "JSON-Pfad",
  hash: "SHA-256",
  search: "Datensätze suchen",
  chooseDataset: "Datensatz auswählen",
  field: "Feld",
  type: "Beobachtete Typen",
  presence: "Datensätze mit Feld",
  nullable: "Fehlend oder null beobachtet",
  yes: "Ja",
  no: "Nein",
  metadataOnly:
    "Nur Felddefinitionen und aggregierte Anzahlen. Persönliche Quellwerte werden nicht angezeigt.",
  graphHint:
    "Wählen Sie einen Knoten für seine direkten Beziehungen. Die Knoten entstehen aus dem geladenen, minimierten Portfoliostand.",
  focus: "Ausgewählter Knoten",
  nodes: "Knoten",
  edges: "Beziehungen",
  owns: "besitzt",
  exposedTo: "Exposition gegenüber",
  client: "Kunde",
  portfolio: "Portfolio",
  assetClass: "Anlageklasse",
  noNeighbors: "Keine direkten Beziehungen in diesem Datenstand.",
  documents: "Projektwissen",
  documentHint:
    "Themeninventar aus dem Wissensgraphen des Repositorys. Dokumente dienen als Referenzkontext und nicht als Laufzeitanweisungen.",
  languages: "Sprachen",
  relation: "Beziehung",
  join: "Verknüpfungsregel",
  meaning: "Bedeutung",
  rule_clientScope:
    "Ein Portfolio gehört zu seinem Quellkunden. Verknüpfungen müssen die Zuordnung bewahren.",
  rule_securityIdentity:
    "Native Positionen über SecurityId verknüpfen. Eine ISIN kann in mehreren Währungszeilen vorkommen.",
  rule_allocationFractions:
    "Dieselbe Allokationsdimension vergleichen. Ziele und Positionsgewichte sind Bruchteile; genau einmal in Prozentpunkte umrechnen.",
  rule_reportedFinding:
    "Dies sind gemeldete Feststellungen des Quellmoduls. Fehlende Meldungen belegen keine vollständige Regelkonformität; Operatorcodes bleiben unentschlüsselt.",
  rule_riskSnapshot:
    "Berechnungsdaten und fehlende Kennzahlen bewahren. Erwartete Rendite ist keine realisierte Performance.",
  rule_lookthroughUnits:
    "Fondsdurchschaugewichte sind Prozentpunkte. Einmal durch 100 teilen und negative Expositionen sichtbar lassen.",
  rule_draftOnly:
    "Vorschläge sind Entwürfe. Diese Transaktionen belegen weder eine Ausführung noch ein vollständiges Handelsjournal.",
  available: "Verfügbar",
  unavailable: "Nicht verfügbar",
  loading: "Prüfdaten werden geladen…",
  failed:
    "Prüfdaten konnten nicht geladen werden. Dienst prüfen und erneut versuchen.",
  retry: "Erneut versuchen",
  role: "Rolle",
  mode: "Modus",
  deterministic: "Deterministisch",
  model: "Modellgestützt",
  input: "Eingabe",
  output: "Ausgabe",
  evidence: "Quellenreferenzen",
  workflow: "Ausführungsablauf",
  boundaries: "Laufzeitgrenzen",
  capability: "Funktion",
  enabled: "Aktiviert",
  disabled: "Deaktiviert",
  chat: "Gespräch",
  images: "Bilderzeugung",
  externalTools: "Externe Werkzeuge",
  persistentMemory: "Dauerhafter Speicher",
  schedules: "Geplante Aufgaben",
  outcomes: "Letzte Ergebnisse",
  outcomeHint:
    "Gemeinsame Demoergebnisse bleiben nur in diesem Prozess erhalten und gehen beim Neustart verloren.",
  noOutcomes:
    "Noch keine abgeschlossenen Ausführungen. Starten Sie ein Gespräch in der Berateransicht.",
  status: "Status",
  checks: "Verifikationsprüfungen",
  warnings: "Hinweise",
  active: "Aktiv",
  profile: "Ausführungsprofil",
  deniedActions: "Gesperrte Aktionen",
  runtimeHint:
    "Die Verfügbarkeit spiegelt die aktuelle Registerabfrage wider. Funktionsmerkmale beschreiben unterstützte Funktionen; die Anbieterausführung kann trotzdem fehlschlagen.",
  detail: "Details",
  openDataset: "Felder dieses Datensatzes prüfen",
  overviewHint:
    "Geladene Anzahlen stammen vom Datendienst; Quellensammlungen beschreiben die versionierten Eingabedateien.",
  signOut: "Abmelden",
  empty: "Keine passenden Datensätze.",
  rawMetadata:
    "Technische Metadaten verwenden das ursprüngliche Quellvokabular.",
  showMore: "Mehr anzeigen",
  accepted: "Akzeptiert",
  rejected: "Abgelehnt",
  revision: "Überarbeitung nötig",
  bounded: "Begrenzter sequenzieller Ablauf",
};
