export const en = {
  adminView: "Admin view",
  adminHint: "Inspect shared demonstration data and runtime in read-only mode",
  advisorView: "Advisor view",
  title: "Data & runtime",
  subtitle: "Inspect the evidence behind every conversation.",
  readonly: "Shared demo · read-only",
  disclosure:
    "This view uses your existing demo session. It does not grant administrator privileges or permit data changes.",
  overview: "Overview",
  datasets: "Datasets",
  structure: "Data structure",
  "knowledge-graph": "Knowledge graph",
  ontology: "Ontology",
  agents: "Agents",
  skills: "Skills",
  runtime: "Runtime",
  refresh: "Refresh",
  refreshHint: "Reload dataset counts and current runtime availability",
  checked: "Checked",
  sourceSnapshot: "Source snapshot",
  loadedData: "Loaded data",
  clients: "Clients",
  portfolios: "Portfolios",
  holdings: "Positions",
  violations: "Reported findings",
  sourceCollections: "Source collections",
  documentTopics: "Knowledge topics",
  valuation: "Risk calculation period",
  dataWarning:
    "Source dates may be shifted. Price and risk calculation dates keep their source semantics.",
  missingYtd: "Portfolios without supplied YTD performance",
  missingHint:
    "Missing performance is unavailable, never zero. Historical NAV changes are not verified investment returns.",
  sourceHint:
    "These counts and field definitions were generated from the supplied JSON snapshot. They are metadata, not a live source-system connection.",
  generated: "Catalog generated",
  records: "Records",
  fields: "Fields",
  source: "Source",
  locator: "JSON location",
  hash: "SHA-256",
  search: "Search datasets",
  chooseDataset: "Choose a dataset",
  field: "Field",
  type: "Observed types",
  presence: "Records with field",
  nullable: "Missing or null observed",
  yes: "Yes",
  no: "No",
  metadataOnly:
    "Field definitions and aggregate counts only. Source personal values are not exposed.",
  graphHint:
    "Select a node to inspect its direct relationships. Nodes are built from the loaded, minimized portfolio snapshot.",
  focus: "Focus node",
  nodes: "Nodes",
  edges: "Relationships",
  owns: "owns",
  exposedTo: "exposed to",
  client: "Client",
  portfolio: "Portfolio",
  assetClass: "Asset class",
  noNeighbors: "No direct relationships in this snapshot.",
  documents: "Project knowledge",
  documentHint:
    "Topic inventory from the repository knowledge graph. These documents are reference context, not runtime instructions.",
  languages: "Languages",
  relation: "Relation",
  join: "Join rule",
  meaning: "Interpretation",
  rule_clientScope:
    "A portfolio belongs to its source client. Joins must preserve ownership.",
  rule_securityIdentity:
    "Join native positions by SecurityId. An ISIN can occur in more than one currency row.",
  rule_allocationFractions:
    "Compare the same allocation dimension. Targets and position weights are fractions; display percentage points once.",
  rule_reportedFinding:
    "These are reported engine findings. Missing findings do not prove all rules passed; operator codes remain undecoded.",
  rule_riskSnapshot:
    "Preserve calculation dates and missing metrics. Expected return is not realized performance.",
  rule_lookthroughUnits:
    "Fund look-through weights are percentage points. Divide by 100 once and keep negative exposures visible.",
  rule_draftOnly:
    "Proposals are drafts. Transactions here do not establish execution or a complete trading ledger.",
  available: "Available",
  unavailable: "Unavailable",
  loading: "Loading inspection data…",
  failed: "Inspection data could not be loaded. Check the service and retry.",
  retry: "Retry",
  role: "Role",
  mode: "Mode",
  deterministic: "Deterministic",
  model: "Model-assisted",
  input: "Input",
  output: "Output",
  evidence: "Source references",
  workflow: "Execution workflow",
  boundaries: "Runtime boundaries",
  capability: "Capability",
  enabled: "Enabled",
  disabled: "Disabled",
  chat: "Conversation",
  images: "Image generation",
  externalTools: "External tools",
  persistentMemory: "Persistent memory",
  schedules: "Scheduled jobs",
  outcomes: "Recent outcomes",
  outcomeHint:
    "Shared demonstration outcomes are retained only in this process and are lost when it restarts.",
  noOutcomes:
    "No completed runs in this process yet. Start a conversation in the advisor view.",
  status: "Status",
  checks: "Verification checks",
  warnings: "Warnings",
  active: "Active",
  profile: "Execution profile",
  deniedActions: "Blocked actions",
  runtimeHint:
    "Availability reflects the current registry request. Capability flags describe supported features; provider execution can still fail.",
  detail: "Details",
  openDataset: "Inspect fields for this dataset",
  overviewHint:
    "Loaded counts come from the data service; source collection counts describe the versioned input files.",
  signOut: "Sign out",
  empty: "No matching datasets.",
  rawMetadata: "Technical metadata is shown in its original source vocabulary.",
  showMore: "Show more",
  accepted: "Accepted",
  rejected: "Rejected",
  revision: "Needs revision",
  bounded: "Bounded sequential workflow",
};
