import type { AdminMessages } from "./messages";
export const es: AdminMessages = {
  adminView: "Vista de administración",
  adminHint:
    "Consultar datos de demostración compartidos y ejecución en modo de solo lectura",
  advisorView: "Vista del asesor",
  title: "Datos y ejecución",
  subtitle: "Consulta la evidencia detrás de cada conversación.",
  readonly: "Demo compartida · solo lectura",
  disclosure:
    "Esta vista utiliza tu sesión de demostración actual. No otorga privilegios de administrador ni permite modificar datos.",
  overview: "Resumen",
  datasets: "Conjuntos de datos",
  structure: "Estructura de datos",
  "knowledge-graph": "Grafo de conocimiento",
  ontology: "Ontología",
  agents: "Agentes",
  skills: "Habilidades",
  runtime: "Ejecución",
  refresh: "Actualizar",
  refreshHint: "Recargar los recuentos y la disponibilidad actual del sistema",
  checked: "Comprobado",
  sourceSnapshot: "Instantánea de origen",
  loadedData: "Datos cargados",
  clients: "Clientes",
  portfolios: "Carteras",
  holdings: "Posiciones",
  violations: "Alertas comunicadas",
  sourceCollections: "Colecciones de origen",
  documentTopics: "Temas de conocimiento",
  valuation: "Periodo de cálculo del riesgo",
  dataWarning:
    "Las fechas de origen pueden estar desplazadas. Las fechas de precios y cálculo del riesgo conservan su significado original.",
  missingYtd: "Carteras sin rentabilidad anual suministrada",
  missingHint:
    "La rentabilidad ausente no está disponible; nunca equivale a cero. Los cambios históricos del valor liquidativo no son rentabilidades verificadas.",
  sourceHint:
    "Estos recuentos y campos se generaron a partir de los JSON suministrados. Son metadatos, no una conexión en vivo al sistema de origen.",
  generated: "Catálogo generado",
  records: "Registros",
  fields: "Campos",
  source: "Origen",
  locator: "Ubicación JSON",
  hash: "SHA-256",
  search: "Buscar conjuntos de datos",
  chooseDataset: "Elegir un conjunto de datos",
  field: "Campo",
  type: "Tipos observados",
  presence: "Registros con el campo",
  nullable: "Ausencia o nulo observado",
  yes: "Sí",
  no: "No",
  metadataOnly:
    "Solo definiciones de campos y recuentos agregados. No se exponen valores personales del origen.",
  graphHint:
    "Selecciona un nodo para consultar sus relaciones directas. Los nodos proceden de la instantánea minimizada de carteras cargada.",
  focus: "Nodo seleccionado",
  nodes: "Nodos",
  edges: "Relaciones",
  owns: "posee",
  exposedTo: "exposición a",
  client: "Cliente",
  portfolio: "Cartera",
  assetClass: "Clase de activo",
  noNeighbors: "No hay relaciones directas en esta instantánea.",
  documents: "Conocimiento del proyecto",
  documentHint:
    "Inventario de temas del grafo de conocimiento del repositorio. Los documentos son contexto de referencia, no instrucciones de ejecución.",
  languages: "Idiomas",
  relation: "Relación",
  join: "Regla de unión",
  meaning: "Interpretación",
  rule_clientScope:
    "Cada cartera pertenece a su cliente de origen. Las uniones deben preservar la titularidad.",
  rule_securityIdentity:
    "Relacionar posiciones nativas por SecurityId. Un ISIN puede aparecer en varias filas de moneda.",
  rule_allocationFractions:
    "Comparar la misma dimensión de asignación. Los objetivos y pesos son fracciones; convertir a puntos porcentuales una sola vez.",
  rule_reportedFinding:
    "Son alertas del motor de origen. Su ausencia no demuestra el cumplimiento de todas las reglas; los códigos de operador siguen sin descifrarse.",
  rule_riskSnapshot:
    "Conservar las fechas de cálculo y las métricas ausentes. La rentabilidad esperada no es la rentabilidad realizada.",
  rule_lookthroughUnits:
    "Los pesos del desglose de fondos son puntos porcentuales. Dividir por 100 una sola vez y mantener visibles las exposiciones negativas.",
  rule_draftOnly:
    "Las propuestas son borradores. Estas transacciones no demuestran ejecución ni constituyen un historial completo de operaciones.",
  available: "Disponible",
  unavailable: "No disponible",
  loading: "Cargando datos de consulta…",
  failed:
    "No se pudieron cargar los datos. Comprueba el servicio e inténtalo de nuevo.",
  retry: "Reintentar",
  role: "Rol",
  mode: "Modo",
  deterministic: "Determinista",
  model: "Asistido por modelo",
  input: "Entrada",
  output: "Salida",
  evidence: "Referencias de origen",
  workflow: "Flujo de ejecución",
  boundaries: "Límites de ejecución",
  capability: "Capacidad",
  enabled: "Activada",
  disabled: "Desactivada",
  chat: "Conversación",
  images: "Generación de imágenes",
  externalTools: "Herramientas externas",
  persistentMemory: "Memoria persistente",
  schedules: "Tareas programadas",
  outcomes: "Resultados recientes",
  outcomeHint:
    "Los resultados de la demostración compartida se conservan solo en este proceso y se pierden al reiniciarlo.",
  noOutcomes:
    "Todavía no hay ejecuciones completadas. Inicia una conversación en la vista del asesor.",
  status: "Estado",
  checks: "Comprobaciones de verificación",
  warnings: "Avisos",
  active: "Activa",
  profile: "Perfil de ejecución",
  deniedActions: "Acciones bloqueadas",
  runtimeHint:
    "La disponibilidad refleja la consulta actual del registro. Las capacidades indican funciones admitidas; la ejecución del proveedor aún puede fallar.",
  detail: "Detalles",
  openDataset: "Consultar los campos de este conjunto",
  overviewHint:
    "Los recuentos cargados proceden del servicio de datos; las colecciones de origen describen los archivos de entrada versionados.",
  signOut: "Cerrar sesión",
  empty: "No hay conjuntos coincidentes.",
  rawMetadata:
    "Los metadatos técnicos conservan el vocabulario original del origen.",
  showMore: "Mostrar más",
  accepted: "Aceptado",
  rejected: "Rechazado",
  revision: "Requiere revisión",
  bounded: "Flujo secuencial acotado",
};
