import type { AdminMessages } from "./messages";
export const fr: AdminMessages = {
  adminView: "Vue administration",
  adminHint:
    "Consulter les données de démonstration partagées et l’exécution en lecture seule",
  advisorView: "Vue conseiller",
  title: "Données et exécution",
  subtitle: "Consultez les preuves derrière chaque conversation.",
  readonly: "Démo partagée · lecture seule",
  disclosure:
    "Cette vue utilise votre session de démonstration actuelle. Elle n’accorde aucun droit administrateur et ne permet aucune modification des données.",
  overview: "Vue d’ensemble",
  datasets: "Jeux de données",
  structure: "Structure des données",
  "knowledge-graph": "Graphe de connaissances",
  ontology: "Ontologie",
  agents: "Agents",
  skills: "Compétences",
  runtime: "Exécution",
  refresh: "Actualiser",
  refreshHint:
    "Recharger les volumes de données et la disponibilité actuelle du système",
  checked: "Vérifié",
  sourceSnapshot: "Instantané source",
  loadedData: "Données chargées",
  clients: "Clients",
  portfolios: "Portefeuilles",
  holdings: "Positions",
  violations: "Constats signalés",
  sourceCollections: "Collections sources",
  documentTopics: "Thèmes de connaissance",
  valuation: "Période de calcul du risque",
  dataWarning:
    "Les dates sources peuvent être décalées. Les dates de prix et de calcul du risque conservent leur sens d’origine.",
  missingYtd: "Portefeuilles sans performance annuelle fournie",
  missingHint:
    "Une performance absente est indisponible, jamais égale à zéro. Les variations historiques de valeur liquidative ne sont pas des rendements vérifiés.",
  sourceHint:
    "Ces volumes et définitions de champs proviennent des fichiers JSON fournis. Ce sont des métadonnées, pas une connexion en direct au système source.",
  generated: "Catalogue généré",
  records: "Enregistrements",
  fields: "Champs",
  source: "Source",
  locator: "Emplacement JSON",
  hash: "SHA-256",
  search: "Rechercher des jeux de données",
  chooseDataset: "Choisir un jeu de données",
  field: "Champ",
  type: "Types observés",
  presence: "Enregistrements avec le champ",
  nullable: "Absence ou valeur nulle observée",
  yes: "Oui",
  no: "Non",
  metadataOnly:
    "Définitions de champs et volumes agrégés uniquement. Les valeurs personnelles des sources ne sont pas exposées.",
  graphHint:
    "Sélectionnez un nœud pour consulter ses relations directes. Les nœuds proviennent de l’instantané minimisé des portefeuilles chargés.",
  focus: "Nœud sélectionné",
  nodes: "Nœuds",
  edges: "Relations",
  owns: "détient",
  exposedTo: "exposé à",
  client: "Client",
  portfolio: "Portefeuille",
  assetClass: "Classe d’actifs",
  noNeighbors: "Aucune relation directe dans cet instantané.",
  documents: "Connaissances du projet",
  documentHint:
    "Inventaire des thèmes du graphe de connaissances du dépôt. Ces documents sont un contexte de référence, pas des instructions d’exécution.",
  languages: "Langues",
  relation: "Relation",
  join: "Règle de jointure",
  meaning: "Interprétation",
  rule_clientScope:
    "Un portefeuille appartient à son client source. Les jointures doivent préserver cette relation.",
  rule_securityIdentity:
    "Relier les positions natives par SecurityId. Un ISIN peut apparaître dans plusieurs lignes de devises.",
  rule_allocationFractions:
    "Comparer la même dimension d’allocation. Les objectifs et pondérations sont des fractions ; convertir une seule fois en points de pourcentage.",
  rule_reportedFinding:
    "Ce sont des constats signalés par le moteur source. Leur absence ne prouve pas le respect de toutes les règles ; les codes opérateurs restent indéterminés.",
  rule_riskSnapshot:
    "Conserver les dates de calcul et les métriques absentes. Le rendement attendu n’est pas une performance réalisée.",
  rule_lookthroughUnits:
    "Les pondérations de transparisation des fonds sont des points de pourcentage. Diviser une fois par 100 et laisser visibles les expositions négatives.",
  rule_draftOnly:
    "Les propositions sont des brouillons. Ces transactions ne prouvent pas une exécution et ne constituent pas un journal complet des opérations.",
  available: "Disponible",
  unavailable: "Indisponible",
  loading: "Chargement des données de consultation…",
  failed:
    "Impossible de charger les données. Vérifiez le service et réessayez.",
  retry: "Réessayer",
  role: "Rôle",
  mode: "Mode",
  deterministic: "Déterministe",
  model: "Assisté par modèle",
  input: "Entrée",
  output: "Sortie",
  evidence: "Références sources",
  workflow: "Processus d’exécution",
  boundaries: "Limites d’exécution",
  capability: "Fonction",
  enabled: "Activée",
  disabled: "Désactivée",
  chat: "Conversation",
  images: "Génération d’images",
  externalTools: "Outils externes",
  persistentMemory: "Mémoire persistante",
  schedules: "Tâches planifiées",
  outcomes: "Résultats récents",
  outcomeHint:
    "Les résultats de démonstration partagés restent dans ce processus uniquement et sont perdus à son redémarrage.",
  noOutcomes:
    "Aucune exécution terminée pour le moment. Démarrez une conversation dans la vue conseiller.",
  status: "État",
  checks: "Contrôles de vérification",
  warnings: "Avertissements",
  active: "Active",
  profile: "Profil d’exécution",
  deniedActions: "Actions bloquées",
  runtimeHint:
    "La disponibilité reflète la requête actuelle du registre. Les indicateurs décrivent les fonctions prises en charge ; l’exécution du fournisseur peut encore échouer.",
  detail: "Détails",
  openDataset: "Consulter les champs de ce jeu",
  overviewHint:
    "Les volumes chargés viennent du service de données ; les collections sources décrivent les fichiers d’entrée versionnés.",
  signOut: "Se déconnecter",
  empty: "Aucun jeu correspondant.",
  rawMetadata:
    "Les métadonnées techniques conservent le vocabulaire original de la source.",
  showMore: "Afficher plus",
  accepted: "Accepté",
  rejected: "Rejeté",
  revision: "Révision nécessaire",
  bounded: "Processus séquentiel borné",
};
